name: Deploy - zixtract
env:
   CI: ""
on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Archive Production Artifact
        uses: actions/upload-artifact@v2
        with:
            name: public
            path: public
      - name: Download Artifact
        uses: actions/download-artifact@master
        with:
          name: public
          path: public
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting:zixtract
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
